In [49]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [50]:
RAW = "../data/raw"
CLEAN ="../data/clean"
df = pd.read_csv(f"{RAW}/bikes_master.csv")

In [51]:
df.head()

,bike_id,brand_id,name,brand,segment,fuel_type,is_ev,price_inr,engine_cc,power_bhp,torque_nm,mileage_kmpl,weight_kg,top_speed_kmph,battery_kwh,range_km,launch_year,rating
0,BK001,BR01,Hero Splendor Plus,Hero MotoCorp,Commuter,Petrol,False,72000,97.2,8.02,8.05,80.0,112,95,NaN,NaN,2015,4.2
1,BK002,BR01,Hero HF Deluxe,Hero MotoCorp,Commuter,Petrol,False,58000,97.2,8.02,8.05,85.0,109,90,NaN,NaN,2014,4.0
2,BK003,BR01,Hero Passion Pro,Hero MotoCorp,Commuter,Petrol,False,78000,113.2,9.15,9.89,65.0,118,95,NaN,NaN,2017,4.1
3,BK004,BR01,Hero Glamour,Hero MotoCorp,Commuter,Petrol,False,82000,124.7,10.69,10.60,55.0,125,98,NaN,NaN,2018,4.2
4,BK005,BR01,Hero Xtreme 160R,Hero MotoCorp,Sports,Petrol,False,115000,163.0,15.20,14.00,45.0,149,109,NaN,NaN,2020,4.3

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bike_id         66 non-null     object
 1   brand_id        66 non-null     object
 2   name            66 non-null     object
 3   brand           66 non-null     object
 4   segment         66 non-null     object
 5   fuel_type       66 non-null     object
 6   is_ev           66 non-null     bool
 7   price_inr       66 non-null     int64
 8   engine_cc       50 non-null     float64
 9   power_bhp       66 non-null     float64
 10  torque_nm       65 non-null     float64
 11  mileage_kmpl    50 non-null     float64
 12  weight_kg       66 non-null     int64
 13  top_speed_kmph  66 non-null     int64
 14  battery_kwh     16 non-null     float64
 15  range_km        16 non-null     float64
 16  launch_year     66 non-null     int64
 17  rating          66 non-null     float64
dtypes: bool(1), float64(7), int64(4), object(6)
memory usage: 9.0+ KB

In [53]:
df.describe()

,price_inr,engine_cc,power_bhp,torque_nm,mileage_kmpl,weight_kg,top_speed_kmph,battery_kwh,range_km,launch_year,rating
count,66.000000,50.00000,66.000000,65.000000,50.000000,66.000000,66.000000,16.000000,16.000000,66.000000,66.000000
mean,144772.727273,208.29680,15.508636,22.243538,45.000000,139.045455,110.984848,3.428750,139.562500,2018.272727,4.253030
std,75072.026021,98.48329,10.547755,15.793056,14.628739,31.877377,26.442677,1.996383,56.267183,3.145426,0.230864
min,55000.000000,97.20000,1.060000,8.050000,24.000000,96.000000,45.000000,1.440000,82.000000,2008.000000,3.600000
25%,85750.000000,124.00000,8.020000,10.500000,35.000000,108.250000,90.000000,2.650000,104.000000,2017.000000,4.100000
50%,132500.000000,162.85500,11.995000,18.100000,40.000000,130.000000,106.000000,3.020000,123.000000,2018.000000,4.300000
75%,177250.000000,307.65000,20.650000,28.000000,55.000000,169.000000,129.500000,3.355000,151.750000,2020.000000,4.400000
max,395000.000000,411.00000,43.500000,95.000000,85.000000,199.000000,175.000000,10.300000,307.000000,2024.000000,4.600000

In [54]:
df.isnull().mean() * 100

bike_id            0.000000
brand_id           0.000000
name               0.000000
brand              0.000000
segment            0.000000
fuel_type          0.000000
is_ev              0.000000
price_inr          0.000000
engine_cc         24.242424
power_bhp          0.000000
torque_nm          1.515152
mileage_kmpl      24.242424
weight_kg          0.000000
top_speed_kmph     0.000000
battery_kwh       75.757576
range_km          75.757576
launch_year        0.000000
rating             0.000000
dtype: float64

# Standardizing column extra spaces

In [55]:
df["name"]      = df["name"].str.strip()
df["brand"]     = df["brand"].str.strip()
df["segment"]   = df["segment"].str.strip()
df["fuel_type"] = df["fuel_type"].str.strip()

# filling Missing value

In [56]:
df["mileage_kmpl"] = df["mileage_kmpl"].fillna(0)
df["range_km"]     = df["range_km"].fillna(0)
df["battery_kwh"]  = df["battery_kwh"].fillna(0)
df["engine_cc"]    = df["engine_cc"].fillna(0)

In [57]:
def price_band(p):
    if p < 80000:   return "Budget (Under 80K)"
    elif p < 150000: return "Mid-range (80K–1.5L)"
    elif p < 250000: return "Premium (1.5L–2.5L)"
    else:            return "Luxury (Above 2.5L)"

df["price_band"] = df["price_inr"].apply(price_band)

In [58]:
# Add value score — power per lakh spent
df["value_score"] = round(df["power_bhp"] / (df["price_inr"] / 100000), 2)

In [59]:
# Add efficiency label
df["efficiency"] = df.apply(
    lambda r: r["range_km"] if r["is_ev"] else r["mileage_kmpl"], axis=1
)

In [60]:
df.to_csv(f"{CLEAN}/bikes_clean.csv", index=False)

# Cleaning Sales_monthly

In [61]:
sales = pd.read_csv(f"{RAW}/sales_monthly.csv")

In [62]:
sales.head()

  bike_id brand_id                name  year  month month_date  units_sold
0   BK001     BR01  Hero Splendor Plus  2019      1    2019-01      307450
1   BK001     BR01  Hero Splendor Plus  2019      2    2019-02      297926
2   BK001     BR01  Hero Splendor Plus  2019      3    2019-03      309715
3   BK001     BR01  Hero Splendor Plus  2019      4    2019-04      322845
4   BK001     BR01  Hero Splendor Plus  2019      5    2019-05      296487

In [63]:
sales["month_date"] = pd.to_datetime(sales["month_date"])
sales["year"]       = sales["year"].astype(int)
sales["month"]      = sales["month"].astype(int)
sales["units_sold"] = sales["units_sold"].fillna(0).astype(int)
sales["name"]       = sales["name"].str.strip()

In [64]:
# Add quarter column
sales["quarter"] = sales["month"].apply(
    lambda m: f"Q{(m-1)//3+1}"
)

In [65]:
# Add festive flag
sales["is_festive"] = sales["month"].isin([9, 10, 11])

In [66]:
# Add COVID flag
sales["is_covid"] = (
    ((sales["year"] == 2020) & (sales["month"].isin([3,4,5,6]))) |
    ((sales["year"] == 2021) & (sales["month"].isin([4,5])))
)

In [67]:
sales.to_csv(f"{CLEAN}/sales_clean.csv", index=False)

# Cleaning EV STATE WISE

In [68]:
states = pd.read_csv(f"{RAW}/ev_state_wise.csv")

In [69]:
states["month_date"]      = pd.to_datetime(states["month_date"])
states["state"]           = states["state"].str.strip()
states["ev_registrations"]= states["ev_registrations"].fillna(0).astype(int)
states["charging_stations"]= states["charging_stations"].fillna(0).astype(int)

In [70]:
# Add region mapping
region_map = {
    "Maharashtra":"West","Gujarat":"West","Rajasthan":"West",
    "Delhi":"North","Uttar Pradesh":"North","Punjab":"North","Haryana":"North","Himachal Pradesh":"North",
    "Karnataka":"South","Tamil Nadu":"South","Telangana":"South","Andhra Pradesh":"South","Kerala":"South",
    "West Bengal":"East","Odisha":"East","Bihar":"East","Jharkhand":"East","Assam":"East",
    "Madhya Pradesh":"Central","Chhattisgarh":"Central"
}

In [71]:
states["region"] = states["state"].map(region_map)

In [72]:
states.to_csv(f"{CLEAN}/ev_states_clean.csv", index=False)

# Cleaning CUSTOMER REVIEWS

In [73]:
reviews = pd.read_csv(f"{RAW}/customer_reviews.csv")

In [74]:
reviews["bike_name"] = reviews["bike_name"].str.strip()
reviews["brand"]     = reviews["brand"].str.strip()
reviews["rating"]    = reviews["rating"].clip(1, 5)

In [75]:
# Sentiment bucket
reviews["sentiment"] = reviews["rating"].apply(
    lambda r: "Positive" if r >= 4 else ("Neutral" if r >= 3 else "Negative")
)

In [76]:
reviews.to_csv(f"{CLEAN}/reviews_clean.csv", index=False)